#pragma once
#ifndef _DEBUG
#else
#pragma comment(lib, "tesseractlib/debug/archive.lib")
#pragma comment(lib, "tesseractlib/debug/bz2d.lib")
#pragma comment(lib, "tesseractlib/debug/charset.lib")
#pragma comment(lib, "tesseractlib/debug/gif.lib")
#pragma comment(lib, "tesseractlib/debug/iconv.lib")
#pragma comment(lib, "tesseractlib/debug/jpegd.lib")
#pragma comment(lib, "tesseractlib/debug/leptonica-1.80.0d.lib")
#pragma comment(lib, "tesseractlib/debug/libcrypto.lib")
#pragma comment(lib, "tesseractlib/debug/libpng16d.lib")
#pragma comment(lib, "tesseractlib/debug/libssl.lib")
#pragma comment(lib, "tesseractlib/debug/libwebpmuxd.lib")
#pragma comment(lib, "tesseractlib/debug/libxml2.lib")
#pragma comment(lib, "tesseractlib/debug/lz4d.lib")
#pragma comment(lib, "tesseractlib/debug/lzmad.lib")
#pragma comment(lib, "tesseractlib/debug/lzo2.lib")
#pragma comment(lib, "tesseractlib/debug/openjp2.lib")
#pragma comment(lib, "tesseractlib/debug/tesseract41d.lib")
#pragma comment(lib, "tesseractlib/debug/tiffd.lib")
#pragma comment(lib, "tesseractlib/debug/tiffxxd.lib")
#pragma comment(lib, "tesseractlib/debug/turbojpegd.lib")
#pragma comment(lib, "tesseractlib/debug/webpd.lib")
#pragma comment(lib, "tesseractlib/debug/webpdecoderd.lib")
#pragma comment(lib, "tesseractlib/debug/webpdemuxd.lib")
#pragma comment(lib, "tesseractlib/debug/xxhash.lib")
#pragma comment(lib, "tesseractlib/debug/zlibd.lib")
#pragma comment(lib, "tesseractlib/debug/zstd_staticd.lib")
#endif // !_DEBUG
